currWeather/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weather/',include('weather.urls'))
]

weather/urls.py
from . import views
from django.conf.urls import url

app_name='weather'

urlpatterns = [

    url(r'^$',views.index),
    #/weather/find/
    url(r'^find/',views.find,name='find')
]

weather/models.py
from django.db import models

class Location(models.Model):
    pincode=models.CharField(max_length=20)
    country=models.CharField(max_length=100)


    def __str__(self):
        return self.pincode+"-"+self.country

weather/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse
from . models import Location
import requests,json


def index(request):
    return render(request,'weather/index.html')

def find(request):
    code=None
    if request.method=="GET":

        code=request.GET.get('Location')
        country=request.GET.get('Country')

    data = {'zip': str(code) + ','+ str(country),'appid': 'e913baa7097c2f6aff9fc7522b2bb095'}
    r = requests.get('http://api.openweathermap.org/data/2.5/weather?', params=data)
    data = json.loads(r.text)
    tempk = (data['main']['temp'])
    tempInCel = float(tempk - 273.15)
    x={"pin":code,"tempInCel":tempInCel}
    context={"code":code,"tempInCel":str(tempInCel),"Country":country}
    return render_to_response("weather/weath.html",context)

weather/templates/weather/index.html
{% load staticfiles %}
<head>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Futura" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static "weather/styles.css" %}"/>
<script src="{% static "weather/js.js" %}" type="text/javascript"></script>
</head>

<div class="user">
    <header class="user__header">

        <h1 class="user__title"><strong>Find the weather of any city</strong></h1><br>
        <h2>Enter the Pincode along with Country Code</h2>
    </header>

    <form class="form" action="{% url "weather:find" %}" align="center" method="GET">
        {% csrf_token %}
        <div class="form__group">
            <input type="text" class="form__input" placeholder="Pincode" name="Location" id="Location"/>
        </div>

        <div class="form__group">
            <input type="text" class="form__input" placeholder="Country" name="Country" id="Country" />
        </div>
        <button class="btn" type='submit'><strong>Submit</strong></button>
    </form>
</div>

weather/templates/weather/indexx.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static "weather/styles.css" %}"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
<script src="{% static "weather/js.js" %}" type="text/javascript"></script>
</head>
<body>

<div class="user">
    <header class="user__header">
        <img src="{% static "weather/images/images.jpg"  %}" alt="" />
        <h1 class="user__title"><strong>Find the weather of any city</strong></h1>
    </header>

    <form class="form" action="{% url "weather:find" %}" align="center" method="GET">
        {% csrf_token %}
        <div class="form__group">
            <input type="text" class="form__input" placeholder="Pincode" name="Location" id="Location"/>
        </div>

        <div class="form__group">
            <input type="email" class="form__input" placeholder="Country" name="Country" id="Country" />
        </div>
        <button class="btn" type='submit'>Submit</button>
    </form>
</div>
</body>

weather/templates/weather/weath.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static "weather/style/style.css" %}"/>
</head>


<h2 align="center"><strong>The weather for pincode {{ code }} is:</strong> {{ tempInCel }}°C</h2>